export const path = {
  // Admin
  login: "/login",
  signup: "/signup",
  dashboard: "/admin/dashboard",
  profile: "/admin/profile",
  adminCategories: "/admin/categories",
  adminArticles: "/admin/articles",
  adminGalleries: "/admin/galleries",
  adminBrands: "/admin/brands",
  adminBrandTypes: "/admin/brand-types",
  adminCountries: "/admin/countries",
  adminDestinations: "/admin/destinations",
  adminInterests: "/admin/interests",
  adminRegions: "/admin/regions",
  adminTickets: "/admin/tickets",

  // CRUD Admin
  createCountry: "/admin/countries/create",
  editCountry: "/admin/countries/edit",
  createRegion: "/admin/regions/create",
  editRegion: "/admin/regions/edit",
  createInterest: "/admin/interests/create",
  editInterest: "/admin/interests/edit",
  createArticle: "/admin/articles/create",
  editArticle: "/admin/articles/edit",
  createDestination: "/admin/destinations/create",
  editDestination: "/admin/destinations/edit",
  createGallery: "/admin/galleries/create",
  editGallery: "/admin/galleries/edit",
  createBrand: "/admin/brands/create",
  editBrand: "/admin/brands/edit",
};
